<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Json\Protocols\*.json" />
  </ItemGroup>

<!--<ItemGroup>
    <None Include="ProtocolGen\*.cs" />
	<Compile Remove="ProtocolGen\*.cs"/>
</ItemGroup>-->

  <ItemGroup>
    <EmbeddedResource Include="Json\Protocols\*.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MPQArchive\MPQArchive.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Parser\" />
    <Folder Include="ProtocolGen\" />
  </ItemGroup>
</Project>
