<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
	
  <PropertyGroup>
  	<DebugType>pdbonly</DebugType>
  	<DebugSymbols>true</DebugSymbols>
  	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
  </ItemGroup>

</Project>
